### ISSUE TITLE
The application doesn't work on Android 5.0 Lollipop

### ISSUE THREAD

**Issue by pasin** [couchbaselabs/TodoLite-PhoneGap#15]
The app has been tested with https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin.

See the attached image for the result.

![screen](https://cloud.githubusercontent.com/assets/801454/5511762/ffa7aaf0-8786-11e4-9a56-d4b68721652f.jpg)

**Comment by pasin** [comment]
@hideki could you look at this issue? It has the issue only with Lollipop.

**Comment by hideki** [comment]
I tested ToDo Lite for PhoneGap with Nexus 6 (Real device), Standard Android Emulator with Nexus 5 API 21 ARM, and Genymotion API 21. But I could not reproduce this this issue with these three platforms.

**Comment by zebra1024** [comment]
I have this same issue on my Verizon Galaxy S5 (SM-G900V) running Android version 5

**Comment by hideki** [comment]
Hi @zebra1024 
Could you please try to recreate ToDo Lite PhoneGap app from scratch with following README's instruction? https://github.com/couchbaselabs/TodoLite-PhoneGap/blob/master/README.md
As @pasin created PhoneGap plugin with CBL Android 1.0.4 recently, I assume it solved this issue.
Thanks!

**Comment by zebra1024** [comment]
Thanks - 1.0.4 resolved the issue.

**Comment by pasin** [comment]
It seems to me that this issue randomly happens as it also happened to me when I tested 1.0.4 before publishing. We may need to keep an eye up on this issue.
