### ISSUE TITLE
Android: After log in Facebook, Javascript codes are displayed on UI. 

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/TodoLite-PhoneGap#24]
Platform: Genymotion  - Android 4.4.4
CBL PhoneGap plugin version: 1.3.1-10

Steps to reproduce:
- Install ToDoLite PhoneGap
- Click login button, and Facebook login page is displayed.
- Fill out credentials and click login 
- JavaScript codes are displayed on screen.

Note: By reloading page, all functionalities are functioning.
Note: With current release version (1.3.0), I don't see this issue.

![screen shot 2016-08-30 at 3 11 08 pm](https://cloud.githubusercontent.com/assets/15889/18109107/5c5cf586-6ec4-11e6-8fae-ddc00bebfe11.png)

**Comment by pasin** [comment]
Can you investigate if it's lite, facebook, or todolite issue?

**Comment by hideki** [comment]
I retested ToDoLite-PhoneGap with using 1.3.1-11 on 09/09/2016. The issue is no longer reproducible. I believe this is Facebook issue.
http://latestbuilds.hq.couchbase.com/couchbase-lite-phonegap/release/1.3.1/1.3.1-11

<img width="656" alt="screen shot 2016-09-09 at 9 29 43 pm" src="https://cloud.githubusercontent.com/assets/15889/18407985/2276b988-76d5-11e6-8d20-de9615908e92.png">
<img width="650" alt="screen shot 2016-09-09 at 9 30 21 pm" src="https://cloud.githubusercontent.com/assets/15889/18407986/279b96b8-76d5-11e6-9d26-c667b9138315.png">
